name: unzip
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^3.4.10
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  file_saver: ^0.2.12
  file_picker: ^9.0.1
  shared_preferences: ^2.5.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

